### ISSUE TITLE
Can't use built in Styles

### ISSUE THREAD

**Issue by Alec321** [chenckang/react-json-pretty#11]
Maybe I'm dumb but no matter what I try the built-in styles don't seem to be working.

**Comment by hrstkatomas** [comment]
I think that the whole approach with the styles is wrong here. They are forcing users to use another loader just because of few color definitions.
I would suggest using bare css, it would not be hard in this case, or distribute built styles.

**Comment by Alec321** [comment]
I am stating that according to the readme styles do not work. This is a bug based on the information in the readme. I was using this library for the flexibility of built-in styling to reduce the work of writing CSS. I instead switched to a different plugin that worked fine with built-in styling and also had collapsable JSON.

**Comment by chenckang** [comment]
Sorry, haven't open the page for a long time. The bare css file is actually in the folder `src`. It seems that you want to use the `style` property? 
Anyway, the trouble have been solved. If you have some suggestions, please reopen this comment and leave some messages.

**Comment by hrstkatomas** [comment]
Ok, let me just sum up the solution here.
Instead of using `import 'react-json-pretty/JSONPretty.monikai.styl';` with webpack `style!css!stylus` loader, people should be able to load styles via `import 'react-json-pretty/src/JSONPretty.monikai.css';` with their css loader of choice.

**Comment by chenckang** [comment]
Have taken some times to upgrade it to 2.0.0, which will boost the developing experience, and also solve a bunch of issues including yours. Read the `readme.md` to get the details.
