### ISSUE TITLE
XSS security problem

### ISSUE THREAD

**Issue by Anderson-Liu** [chenckang/react-json-pretty#13]
If give some data like this to the component,  it will execute js and get cookie:
```
const data = `{data: \"<img onerror='alert(document.cookie)' src='invalid-image' />}`
```
```javascript
<JSONPretty id="json-pretty" data={data} />
```

People all using this component should be careful about input and do more check.

This is because this component use `dangerouslySetInnerHTML`;

![image](https://user-images.githubusercontent.com/8468372/53866174-e7e7a480-402b-11e9-8a88-e845f65116d5.png)

I think people should be warned in `README` about it before start using this component.

**Comment by chenckang** [comment]
fixed in v2.0.1
