### ISSUE TITLE
Built-in TypeScript definitions aren't used

### ISSUE THREAD

**Issue by markdascher** [chenckang/react-json-pretty#14]
Bumped into two issues trying to use the built-in TypeScript definitions.

```
error TS7016: Could not find a declaration file for module 'react-json-pretty'.
error TS2322: Type '…' is not assignable to type '…'.
              Property '…' does not exist on type '…'.
```

First, package.json needs a line like [this](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package), under the `"main": "dist/JSONPretty.js",` definition:

```
  "types": "types/JSONPretty.d.ts",
```

Second, since `...rest` is passed through to a div, that implies IProps can accept more than the eight defined props. One way of making that happen is to replace line 5 of JSONPretty.tsx with:

```
interface IProps extends React.HTMLAttributes<React.HTMLDivElement> {
```

**Comment by chenckang** [comment]
fixed in the version 2.2.0
