### ISSUE TITLE
Padding property on JSONPretty

### ISSUE THREAD

**Issue by fnoah** [chenckang/react-json-pretty#15]
I think it is a common usecase to have a CSS `padding` property on `__json-pretty__` in order to have a padding between where the background color ends and the code starts. Instead of having to add this in a CSS maybe it would make sense to have a property on `JSONPretty`:

```javascript
<JSONPretty
    id="json-pretty"
    margin={20}
    data={data}
></JSONPretty>
```

**Comment by chenckang** [comment]
https://github.com/chenckang/react-json-pretty#using-typestyle-property

**Comment by chenckang** [comment]
supported in version 2.2.0
