### ISSUE TITLE
Bug with backslash at the end of a string

### ISSUE THREAD

**Issue by mosino** [chenckang/react-json-pretty#2]
Hi,

first of all, thanks for the great module!

A little bug that I encountered lately: If a property ends with a backslash, then this last backslash is not escaped correctly:

Reproduce:

`<JSONPretty json={{a: "b\\"}}></JSONPretty>`
results in

```
{
  "a": "b\"
}
```
but should result in 
```
{
  "a": "b\\"
}
```

Also the colors are not right in this case

**Comment by chenckang** [comment]
Roger，the bug will fixed as soon as possible!

2016-12-23 21:09 GMT+08:00 marcata <notifications@github.com>:

**Comment by chenckang** [comment]
Hi：

Thx for your report, the bug has been solved, and bug-fixed version is
1.2.2.

We hope you like it.

O(∩_∩)O~

2016-12-29 13:56 GMT+08:00 Kang Chen <chenckang@gmail.com>:

**Comment by mosino** [comment]
Wow, I didn't expect such a quick response. Thanks again!
