### ISSUE TITLE
npm shrinkwrap causes peer invalid error

### ISSUE THREAD

**Issue by vasya10** [chenckang/react-json-pretty#4]
Hi,

Im using react-json-pretty 1.4.0 with React 15. Nodejs is 4.6.2. I have tried a few versions of npm (3.8, 3.10, 4.x). When executing npm shrinkwrap --dev, I get an error: peer invalid: react@^0.14.3, required by react-json-pretty@1.4.0

Any chances of updating the package to use react 15?

Appreciate any help.

**Comment by chenckang** [comment]
Hi,

The react-json-pretty@1.5.0 has been published, and the peerDependencies version has been changed to adapt to a very large versions of react&react-dom，which will satisfy your demonds.

In the example project, testing shows that everything is ok, including the `npm shrink` command.

If there are any other questions, welcome to create an issue to show them.

Thanks

**Comment by chenckang** [comment]
Close the issue.
