### ISSUE TITLE
Warning: exports: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### ISSUE THREAD

**Issue by MartinDawson** [chenckang/react-json-pretty#5]
Warning: exports: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Can we get this fixed please? Thanks.

**Comment by chenckang** [comment]
This problem is solved on the version >=1.6.0 which uses peer dependencies of react version >=15.5.0.

try to use `npm install --save react-json-pretty@1.6.1` to install the newest version.

Any additional issues are welcome, thanks.
