### ISSUE TITLE
Strip down npm publish

### ISSUE THREAD

**Issue by dyst5422** [chenckang/react-json-pretty#7]
Please consider working on your packaging for npm publish. Currently, having the .babelrc as part of the published contents causes headaches with many build systems.  Simply having a .npmignore would help a lot.

**Comment by chenckang** [comment]
Thanks for you advice. But would you please provide some description about the problem you encounter, so that I can understand more about what happened.

**Comment by chenckang** [comment]
Any way, .npmignore  is added and published with the version 1.7.4.

So you can try to use react-json-pretty@1.7.4. 

You are welcome to give any advice.

**Comment by dyst5422** [comment]
Just confirmed this works like a charm now. Thanks!
