### ISSUE TITLE
Bug with : in key

### ISSUE THREAD

**Issue by mnaveenriaz** [chenckang/react-json-pretty#9]
When the JSON key has ':', the same is removed when pretty printing the same.

"react": "^16.2.0",
"react-jsonschema-form": "^1.0.0",
"react-json-pretty": "^1.7.4",

Edit mode where the JSON is within a textarea

![screen shot 2018-03-28 at 12 43 07 am](https://user-images.githubusercontent.com/10970565/37981757-1d8c7e9a-3221-11e8-9dd2-72d2e179b5de.png)

View mode where JSON is pretty printed.
![screen shot 2018-03-28 at 12 42 36 am](https://user-images.githubusercontent.com/10970565/37981760-1dc45a4a-3221-11e8-9a50-8d8b05a4e526.png)

**Comment by chenckang** [comment]
This is a bug and is fixed in the version 1.7.6.
